"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""


from pathlib import Path
from decouple import config


BASE_DIR = Path(__file__).resolve().parent.parent


# ──────────────────────────────────
SECRET_KEY = config('SECRET_KEY')
DEBUG       = config('DEBUG', cast=bool, default=False)

# ['*'] is safe for this project, because:
# There aren't password reset emails
# There aren't request.build_absolute_uri() calls in any view
# Private local network — an attacker needs physical access to the network first
# Even then, login + 2FA stands between them and anything useful
ALLOWED_HOSTS = ['*']


# ── Installed Apps ────────────────────────────
INSTALLED_APPS = [
    # Django built-ins
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 2FA – django-otp core + TOTP (Google Authenticator)
    'django_otp',
    'django_otp.plugins.otp_totp',
    'django_otp.plugins.otp_static',
    # Brute-force / login-attempt protection
    'axes',
    # apps
    'login',    # login + password-change + 2FA setup
    'cloud',    # Files & Media pages
]


# ── Middleware ────────────────────────────────
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',          # must be AFTER AuthenticationMiddleware
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',               # must be LAST
]


ROOT_URLCONF  = 'core.urls'
WSGI_APPLICATION = 'core.wsgi.application'
CSRF_FAILURE_VIEW = 'login.views.csrf_failure_view'


TEMPLATES = [{
    'BACKEND': 'django.template.backends.django.DjangoTemplates',
    'DIRS': [BASE_DIR / 'templates'],   # global templates/
    'APP_DIRS': True,
    'OPTIONS': { 'context_processors': [
        'django.template.context_processors.debug',
        'django.template.context_processors.request',
        'django.contrib.auth.context_processors.auth',
        'django.contrib.messages.context_processors.messages',
    ]},
}]


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME'  : BASE_DIR / 'data' / 'db.sqlite3',
    },
}



AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',          # ← must be FIRST
    'django.contrib.auth.backends.ModelBackend',
]

LOGIN_URL           = 'login:login'
LOGIN_REDIRECT_URL  = 'cloud:home'       # after full 2FA login -> cloud home
LOGOUT_REDIRECT_URL = 'login:login'


AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# ── django-axes (brute-force protection) ──────
AXES_FAILURE_LIMIT                       = 5     # lock after 5 bad attempts
AXES_COOLOFF_TIME                        = 1     # unlock after 1 hour
AXES_LOCKOUT_PARAMETERS                  = ['ip_address'] # lock by IP only — wrong guesses won't lock the account
AXES_RESET_ON_SUCCESS                    = True  # reset counter on successful login


# ── Static & Media Files ──────────────────────
STATIC_URL  = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # collectstatic output

MEDIA_URL  = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'         # user uploads


# ── Internationalisation ──────────────────────
LANGUAGE_CODE = 'en-us'
TIME_ZONE     = 'UTC'
USE_I18N      = True
USE_TZ        = True


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ── Security Headers ──────────────────────────
X_FRAME_OPTIONS            = 'DENY'     # no iframes
SECURE_CONTENT_TYPE_NOSNIFF = True


# ── Session ───────────────────────────────────
SESSION_COOKIE_AGE              = 7200  # 2-hour inactivity logout (seconds)
SESSION_SAVE_EVERY_REQUEST      = True  # reset the 2h timer on every request (sliding expiry)
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_HTTPONLY         = True  # JS cannot read the session cookie (XSS protection)
SESSION_COOKIE_SAMESITE         = 'Lax' # blocks cross-site POST abuse, keeps redirects working


# ── Default password to detect & force-change ─
# Login view will compare against this constant.
DEFAULT_USERNAME      = 'YouKnow'
DEFAULT_USER_PASSWORD = 'YouKnow12?'


# ── Logging ───────────────────────────────────
LOGGING = {
    'version': 1, 'disable_existing_loggers': False,
    'handlers': {'console': {'class': 'logging.StreamHandler'}},
    'root': {'handlers': ['console'], 'level': 'INFO'},
}

# ── About the cloud part ──────────────────────
# Large file upload support
FILE_UPLOAD_MAX_MEMORY_SIZE = 2621440   # 2.5 MB — files go to disk fast, keeps RAM free
DATA_UPLOAD_MAX_MEMORY_SIZE = None      # None = no size limit on uploads
