# Generated by Django 6.0.4 on 2026-06-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudfile',
            name='original_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='original_name',
            field=models.CharField(max_length=500),
        ),
    ]
